--LAS TABLAS DEL PROYECTO

DROP TABLE Equipo CASCADE CONSTRAINTS;
CREATE TABLE Equipo (
  id_equipo INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE NOT NULL ENABLE
            CONSTRAINT id_eq_pk PRIMARY KEY, --TODO ESTO ES PARA QUE EL ID SEA AUTOINCREMENTAL, EMPEZARÁ EN 1 Y PODRÁ SEGUIR HASTA 999999, ALEATORIAMENTE
  referencia VARCHAR2(4) UNIQUE NOT NULL,          
  nombre VARCHAR2(15) NOT NULL 
  );

DROP TABLE Jugador CASCADE CONSTRAINTS;
CREATE TABLE Jugador (
  id_jugador INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE NOT NULL ENABLE
             CONSTRAINT id_ju_pk PRIMARY KEY,
  dni VARCHAR2(15) UNIQUE NOT NULL,           
  nickname VARCHAR2(15) UNIQUE NOT NULL,
  nombre VARCHAR2(15) NOT NULL,
  sueldo NUMBER(6,2) NOT NULL,
  id_equipo INTEGER NOT NULL,
  
  CONSTRAINT id_eqj_fk FOREIGN KEY(id_equipo) REFERENCES Equipo (id_equipo),
  CONSTRAINT ju_suel CHECK (sueldo>735.90));
  
DROP TABLE Persona CASCADE CONSTRAINTS;
CREATE TABLE Persona (
  id_persona INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE NOT NULL ENABLE
             CONSTRAINT id_pe_pk PRIMARY KEY,
  dni VARCHAR2(9) UNIQUE NOT NULL,           
  nombre VARCHAR2(15) NOT NULL,
  tipo INTEGER NOT NULL,
  id_equipo INTEGER NULL,
  
  CONSTRAINT id_eqp_fk FOREIGN KEY (id_equipo) REFERENCES Equipo (id_equipo));
  
DROP TABLE Login CASCADE CONSTRAINTS;
CREATE TABLE Login (
  id_login INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE NOT NULL ENABLE
           CONSTRAINT id_lo_pk PRIMARY KEY,
  usuario VARCHAR2(15) UNIQUE NOT NULL,
  contraseña VARCHAR2(15) UNIQUE NOT NULL,
  id_persona INTEGER NOT NULL,
  
  CONSTRAINT id_per_fk FOREIGN KEY (id_persona) REFERENCES Persona (id_persona));
  
  
DROP TABLE Jornada CASCADE CONSTRAINTS;  
CREATE TABLE Jornada (
  id_jornada INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE NOT NULL ENABLE
             CONSTRAINT id_jo_pk PRIMARY KEY,
  fec_ini DATE NOT NULL,
  fec_fin DATE NOT NULL
);
  
DROP TABLE Partido CASCADE CONSTRAINTS;
CREATE TABLE Partido (
  id_partido INTEGER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 NOORDER NOCYCLE NOT NULL ENABLE
             CONSTRAINT id_pa_pk PRIMARY KEY,
  fecha DATE NOT NULL,
  puntos_loc INTEGER NOT NULL,
  puntos_vis INTEGER NOT NULL,
  id_jornada INTEGER NOT NULL,
  
  CONSTRAINT id_jo_fk FOREIGN KEY (id_jornada) REFERENCES Jornada (id_jornada));
 
DROP TABLE Juegan CASCADE CONSTRAINTS; 
CREATE TABLE Juegan (
  id_partido INTEGER NOT NULL,
  id_equipo INTEGER NOT NULL,
  
  CONSTRAINT id_pa_fk FOREIGN KEY (id_partido) REFERENCES Partido (id_partido),
  CONSTRAINT id_eqju_fk FOREIGN KEY(id_equipo) REFERENCES Equipo (id_equipo)); 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  