/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisVentanas;

/**
 *
 * @author Aitor Alday
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        cbmJNuevo = new javax.swing.JCheckBoxMenuItem();
        cbmJBorrar = new javax.swing.JCheckBoxMenuItem();
        cbmJModificar = new javax.swing.JCheckBoxMenuItem();
        jMenu8 = new javax.swing.JMenu();
        cbmENuevo = new javax.swing.JCheckBoxMenuItem();
        cbmEBorrar = new javax.swing.JCheckBoxMenuItem();
        cbmEModificar = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cbmPerNuevo = new javax.swing.JMenuItem();
        cbmPerBorrar = new javax.swing.JMenuItem();
        cbmPerModificar = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        cbmCNuevo = new javax.swing.JCheckBoxMenuItem();
        cbmCBorrar = new javax.swing.JCheckBoxMenuItem();
        cbmCModificar = new javax.swing.JCheckBoxMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu10.setText("jMenu10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisVentanas/imagenes/FondoPrincipal.jpg"))); // NOI18N

        jMenu2.setText("Equipos");

        jMenuItem1.setText("Listado de equipos");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Dueño");

        jMenuItem2.setText("Nuevo Equipo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu4.setText("Gestionar equipos");

        jMenuItem6.setText("Eliminar Equipo");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Modificar Equipos");
        jMenu4.add(jMenuItem7);

        jMenu3.add(jMenu4);

        jCheckBoxMenuItem1.setText("Jornada");
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem3.setText("Clasificacion");
        jMenu3.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Administrador");

        jMenu7.setText("Jugadores");

        cbmJNuevo.setText("Nuevo");
        cbmJNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmJNuevoActionPerformed(evt);
            }
        });
        jMenu7.add(cbmJNuevo);

        cbmJBorrar.setText("Eliminar");
        cbmJBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmJBorrarActionPerformed(evt);
            }
        });
        jMenu7.add(cbmJBorrar);

        cbmJModificar.setText("Modificar");
        cbmJModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmJModificarActionPerformed(evt);
            }
        });
        jMenu7.add(cbmJModificar);

        jMenu6.add(jMenu7);

        jMenu8.setText("Equipos");

        cbmENuevo.setText("Nuevo");
        cbmENuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmENuevoActionPerformed(evt);
            }
        });
        jMenu8.add(cbmENuevo);

        cbmEBorrar.setText("Eliminar");
        cbmEBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmEBorrarActionPerformed(evt);
            }
        });
        jMenu8.add(cbmEBorrar);

        cbmEModificar.setText("Modificar");
        cbmEModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmEModificarActionPerformed(evt);
            }
        });
        jMenu8.add(cbmEModificar);

        jMenu6.add(jMenu8);

        jMenu1.setText("Persona");

        cbmPerNuevo.setText("Nuevo");
        cbmPerNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmPerNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(cbmPerNuevo);

        cbmPerBorrar.setText("Eliminar");
        cbmPerBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmPerBorrarActionPerformed(evt);
            }
        });
        jMenu1.add(cbmPerBorrar);

        cbmPerModificar.setText("Modificar");
        cbmPerModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmPerModificarActionPerformed(evt);
            }
        });
        jMenu1.add(cbmPerModificar);

        jMenu6.add(jMenu1);

        jMenu12.setText("Calendario");

        cbmCNuevo.setText("Nuevo");
        cbmCNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCNuevoActionPerformed(evt);
            }
        });
        jMenu12.add(cbmCNuevo);

        cbmCBorrar.setText("Eliminar");
        cbmCBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCBorrarActionPerformed(evt);
            }
        });
        jMenu12.add(cbmCBorrar);

        cbmCModificar.setText("Modificar");
        cbmCModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmCModificarActionPerformed(evt);
            }
        });
        jMenu12.add(cbmCModificar);

        jMenu6.add(jMenu12);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(jLabel2)
                    .addContainerGap(738, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabel2)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cbmJNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmJNuevoActionPerformed
        proyecto.Proyecto.abrirJugador();
    }//GEN-LAST:event_cbmJNuevoActionPerformed

    private void cbmJBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmJBorrarActionPerformed
        proyecto.Proyecto.abrirJugador();
    }//GEN-LAST:event_cbmJBorrarActionPerformed

    private void cbmENuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmENuevoActionPerformed
        proyecto.Proyecto.abrirEquipos('c');
    }//GEN-LAST:event_cbmENuevoActionPerformed

    private void cbmPerNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmPerNuevoActionPerformed
        proyecto.Proyecto.abrirPersona();
    }//GEN-LAST:event_cbmPerNuevoActionPerformed

    private void cbmPerBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmPerBorrarActionPerformed
        proyecto.Proyecto.abrirPersona();
    }//GEN-LAST:event_cbmPerBorrarActionPerformed

    private void cbmPerModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmPerModificarActionPerformed
        proyecto.Proyecto.abrirPersona();
    }//GEN-LAST:event_cbmPerModificarActionPerformed

    private void cbmJModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmJModificarActionPerformed
        proyecto.Proyecto.abrirJugador();
    }//GEN-LAST:event_cbmJModificarActionPerformed

    private void cbmEBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmEBorrarActionPerformed
        proyecto.Proyecto.abrirEquipos('b');
    }//GEN-LAST:event_cbmEBorrarActionPerformed

    private void cbmEModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmEModificarActionPerformed
        proyecto.Proyecto.abrirEquipos('e');
    }//GEN-LAST:event_cbmEModificarActionPerformed

    private void cbmCNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCNuevoActionPerformed
        
    }//GEN-LAST:event_cbmCNuevoActionPerformed

    private void cbmCBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCBorrarActionPerformed
        
    }//GEN-LAST:event_cbmCBorrarActionPerformed

    private void cbmCModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmCModificarActionPerformed
        
    }//GEN-LAST:event_cbmCModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem cbmCBorrar;
    private javax.swing.JCheckBoxMenuItem cbmCModificar;
    private javax.swing.JCheckBoxMenuItem cbmCNuevo;
    private javax.swing.JCheckBoxMenuItem cbmEBorrar;
    private javax.swing.JCheckBoxMenuItem cbmEModificar;
    private javax.swing.JCheckBoxMenuItem cbmENuevo;
    private javax.swing.JCheckBoxMenuItem cbmJBorrar;
    private javax.swing.JCheckBoxMenuItem cbmJModificar;
    private javax.swing.JCheckBoxMenuItem cbmJNuevo;
    private javax.swing.JMenuItem cbmPerBorrar;
    private javax.swing.JMenuItem cbmPerModificar;
    private javax.swing.JMenuItem cbmPerNuevo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
